sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20053
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: kk316113-web-ai
    accessKeyId: 1
    accessKeySecret: 2